MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - "10.14"                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - "10.14"                # [osx and x86_64]
CONDA_BUILD_SYSROOT:       # [osx and x86_64]
  - /opt/MacOSX10.14.sdk   # [osx and x86_64]
macos_min_version:         # [osx and x86_64]
  - "10.14"                # [osx and x86_64]
    #c_compiler_version:        # [osx and x86_64]
    #  - "14.0.6"               # [osx and x86_64]
    #cxx_compiler_version:      # [osx and x86_64]
    #  - "14.0.6"               # [osx and x86_64]
