{% set name = "cmdstanpy" %}
{% set version = "1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stan-dev/cmdstanpy/archive/v{{ version }}.tar.gz
  sha256: c724507353281e20112a8347b97011deffef3d6e413e8a065b85455a6552fc2e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - install_cmdstan = cmdstanpy.install_cmdstan:main
    - install_cxx_toolchain = cmdstanpy.install_cxx_toolchain:main

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - pandas
    - numpy >=1.21
    - ujson
    - cmdstan
    - tqdm


about:
  home: https://mc-stan.org/users/interfaces/cmdstan.html
  dev_url: https://github.com/stan-dev/cmdstanpy
  doc_url: https://cmdstanpy.readthedocs.io
  summary: |
    CmdStanPy is a lightweight interface to Stan for Python users which
    provides the necessary objects and functions to compile a Stan program
    and fit the model to data using CmdStan.
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - maresb
    - WardBrian
